title: User Name's Homepage
page-top-title: Multimodal Fake News Detection 
top-section-bg-text:  多维解析模态，智能甄别不实内容
home-subtitle: 多模态虚假新闻检测插件&ensp;|&ensp;辨别网络信息
copyright-text: '&copy; Multimodal Fake News Detection 2026-6.'
